// Tipos de espaço permitidos
export const SPACE_TYPES = {
    ESPACO_PARA_EVENTOS: 'espaço_para_eventos',
    SALA_DE_REUNIOES: 'sala_de_reuniões',
    AUDITORIO: 'auditório',
    ESPACO_COWORKING: 'espaço_de_coworking',
    ESTUDIO: 'estúdio',
    GALERIA: 'galeria',
    SALAO_FESTAS: 'salao_festas',
    ESPACO_CULTURAL: 'espaco_cultural',
    SALA_TREINO: 'sala_treino',
    SALA_AULA: 'sala_aula',
    ESPACO_GASTRONOMICO: 'espaco_gastronomico',
    ESPACO_BELEZA: 'espaco_beleza',
    ESPACO_MEDICO: 'espaco_medico',
    ESPACO_RELIGIOSO: 'espaco_religioso',
    ESPACO_ESPORTIVO: 'espaco_esportivo',
    ESPACO_TEATRO: 'espaco_teatro',
    ESPACO_MUSICA: 'espaco_musica',
    ESPACO_EXPOSICAO: 'espaco_exposicao',
    ESPACO_WORKSHOP: 'espaco_workshop',
    ESPACO_YOGA: 'espaco_yoga',
    ESPACO_DANCA: 'espaco_danca',
    ESPACO_ARTES_MARCIAIS: 'espaco_artes_marciais',
    ESPACO_FOTOGRAFIA: 'espaco_fotografia',
    ESPACO_GRAFICA: 'espaco_grafica',
    ESPACO_CERIMONIA: 'espaco_cerimonia',
    ESPACO_CONFERENCIA: 'espaco_conferencia',
    ESPACO_SHOWROOM: 'espaco_showroom',
    ESPACO_LOJA: 'espaco_loja',
    ESPACO_ESCRITORIO: 'espaco_escritorio',
    ESPACO_ESTUDIO_TV: 'espaco_estudio_tv',
    ESPACO_ESTUDIO_RADIO: 'espaco_estudio_radio',
    ESPACO_ESTUDIO_PODCAST: 'espaco_estudio_podcast',
    ESPACO_ESTUDIO_GRAVACAO: 'espaco_estudio_gravacao',
    ESPACO_ESTUDIO_DANCA: 'espaco_estudio_danca',
    ESPACO_ESTUDIO_MUSICA: 'espaco_estudio_musica',
    ESPACO_ESTUDIO_ARTE: 'espaco_estudio_arte',
    ESPACO_ESTUDIO_FITNESS: 'espaco_estudio_fitness',
    ESPACO_ESTUDIO_PILATES: 'espaco_estudio_pilates',
    ESPACO_ESTUDIO_MASSAGEM: 'espaco_estudio_massagem',
    ESPACO_ESTUDIO_SPA: 'espaco_estudio_spa',
    ESPACO_ESTUDIO_SAUNA: 'espaco_estudio_sauna',
    ESPACO_ESTUDIO_PISCINA: 'espaco_estudio_piscina',
    ESPACO_ESTUDIO_QUADRA: 'espaco_estudio_quadra',
    ESPACO_ESTUDIO_CAMPO: 'espaco_estudio_campo',
    ESPACO_ESTUDIO_PARQUE: 'espaco_estudio_parque',
    OUTRO: 'outro'
};

// Lista plana de todos os tipos permitidos
export const ALLOWED_SPACE_TYPES = Object.values(SPACE_TYPES); 